### ISSUE TITLE
Not clear how to manage members

### ISSUE THREAD

**Issue by Franchovy** [SUASecLab/workadventure-admin#11]
Hi all,

First off, thank you for your work. This is invaluable considering the self-hosted version doesn't have any ACL by default. I've managed to get the setup up and running and successfully used the "maps" portion of the admin interface.

However, I wanted to know more about the "users" side of things. I've been able to create users, attach tags on them, etc., however I don't see a way to actually **log those users in**. That's strange to me given that the entire point of the ACL is for controlled access (at least by "members" who can be granted special permissions, such as editing rights, megaphone, etc.).

Could you please clarify what is the right course of action for adding/editing/logging in as a member? The "/register" endpoint is not found, and by default self-hosted WA does not even provide a log in/log out feature.

Thank you very much in advance. Please let me know if there's an opportunity to contribute on this project as well.

**Comment by Franchovy** [comment]
Hi @ttefke, apologies for the late reply.

I've spent the last week or so configuring OIDC authentication and now have a locally-hosted provider working. However, I see that the admin API does not use this provider natively. Therefore any logins/signups using the OIDC provider are separate from the ones created via the admin dashboard.

Unfortunately I run into errors when I enable the admin API via the .env file, workadventure fails to start properly due to a map fetch error:

```
Room.ts:228 Error => getMapDetail ApiError: The API returned an error
    at dj.getMapDetail (Room.ts:213:23)
    at async dj.createRoom (Room.ts:92:28)
    at async frg.initGameConnexion (ConnectionManager.ts:322:33)
    at async Alg.init (GameManager.ts:59:24)
getMapDetail @ Room.ts:228
await in getMapDetail
createRoom @ Room.ts:92
initGameConnexion @ ConnectionManager.ts:322
init @ GameManager.ts:59
(anonymous) @ EntryScene.ts:42
Promise.then
loadLocale @ EntryScene.ts:40
create @ EntryScene.ts:31
create @ phaser.js:197569
loadComplete @ phaser.js:197476
n.emit @ phaser.js:200
loadComplete @ phaser.js:119639
fileProcessComplete @ phaser.js:119605
onProcessComplete @ phaser.js:118211
data.onload @ phaser.js:124728
ErrorScreenStore.ts:98 ApiError: The API returned an error
    at dj.getMapDetail (Room.ts:213:23)
    at async dj.createRoom (Room.ts:92:28)
    at async frg.initGameConnexion (ConnectionManager.ts:322:33)
    at async Alg.init (GameManager.ts:59:24)
```

Therefore I'm not really able to test any of the members functionality from within workadventure, I only have the dashboard which works independently of the app itself.

**Comment by ttefke** [comment]
Hello everyone,
Due to inactivity I'll close this issue for now. If any questions or doubts remain, please open a new one.
Kind regards,
Tobias
